services:
  - type: web
    name: eau-vivante-plasma
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    pullRequestPreviewsEnabled: false
    envVars:
      - key: BREVO_API_KEY
        sync: false
